#!/bin/sh
# This script is executed as part of the hotplug event with
# HOTPLUG_TYPE=iface, triggered by various scripts when an interface
# is configured (ACTION=ifup) or deconfigured (ACTION=ifdown).  The
# interface is available as INTERFACE, the real device as DEVICE.

[ "$INTERFACE" = "lan" ] || exit 0

# we don't get symmetrical events for br-lan, so we can't filter by it
#. /etc/dhcp.guest.conf
#[ "$DEVICE" == "$GUEST_DHCP_BRIDGE" ] || exit 0

case "$ACTION" in
        ifup)
                /etc/init.d/guest_dhcp start
        ;;
        ifdown)
                /etc/init.d/guest_dhcp stop
        ;;
esac
