ifeq ($(obj),)
obj := .
endif

DEPTH := ../..

ifeq ($(strip ${QCA_PARTNER_MAKE_F_SUPPORT}),1)
export QCA_PARTNER_MAKE_F_INC=1
endif
include $(obj)/$(DEPTH)/os/linux/Makefile-linux.common

INCS += -I$(HAL) -I$(HAL)/$(OS) -I$(ATH) -I$(ATH_RATE) -I$(ATH_PKTLOG) -I$(ATH_DFS)

INCS += -I$(obj)/$(DEPTH)/umac/include -I$(obj)/$(DEPTH)/umac/if_lmac

obj-m += ath_dfs.o

EXTRA_CFLAGS+= $(INCS) $(COPTS)

ifeq ($(strip ${QCA_PARTNER_MAKE_F_SUPPORT}),1)
MOD_CFLAGS = -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(ath_dfs.mod)"  -D"KBUILD_MODNAME=KBUILD_STR(ath_dfs)" 
endif

ath_dfs-objs := dfs.o dfs_staggered.o dfs_bindetects.o dfs_misc.o dfs_process_radarevent.o dfs_process_phyerr.o dfs_nol.o dfs_fcc_bin5.o dfs_ar.o dfs_init.o dfs_debug.o dfs_phyerr_tlv.o

clean-files := modules.order

ifeq ($(strip ${QCA_PARTNER_MAKE_F_SUPPORT}),1)
all: ath_dfs.ko

ath_dfs.mod.o: ath_dfs.mod.c
	${CC} -c -o $@ ${EXTRA_CFLAGS} ${MOD_CFLAGS} $<

ath_dfs.o: ${ath_dfs-objs}
	$(LD) -m elf32btsmip -r -o ath_dfs.o $(ath_dfs-objs)
	$(KERNELPATH)/scripts/mod/modpost ath_dfs.o

ath_dfs.ko: ath_dfs.o ath_dfs.mod.o
	$(LD) $(LDOPTS) -o ath_dfs.ko ath_dfs.o ath_dfs.mod.o

%.o: %.c 
	${CC} -c -o $@ ${EXTRA_CFLAGS} $<
endif
