#ifndef _IPT_NETGEAR_REJECT_H
#define _IPT_NETGEAR_REJECT_H

enum ipt_netgear_reject_with {
	IPT_NETGEAR_ICMP_NET_UNREACHABLE,
	IPT_NETGEAR_ICMP_HOST_UNREACHABLE,
	IPT_NETGEAR_ICMP_PROT_UNREACHABLE,
	IPT_NETGEAR_ICMP_PORT_UNREACHABLE,
	IPT_NETGEAR_ICMP_ECHOREPLY,
	IPT_NETGEAR_ICMP_NET_PROHIBITED,
	IPT_NETGEAR_ICMP_HOST_PROHIBITED,
	IPT_NETGEAR_TCP_RESET,
	IPT_NETGEAR_ICMP_ADMIN_PROHIBITED,
	IPT_NETGEAR_HTTP_SITE_PROHIBITED,
	IPT_NETGEAR_TRAFFIC_LIMIT
};

struct ipt_netgear_reject_info {
	enum ipt_netgear_reject_with with;      /* netgear_reject type */
};

#endif /*_IPT_NETGEAR_REJECT_H*/
