#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Run original firewall
/usr/sbin/net-wall-bin $*

if [ "$1" = "rule" ]; then
	# Store rules of original firewall
	cat /tmp/netwall-rules > /tmp/netwall-rules.tmp

	# Check config file existence, add own rules if file exists
	if [ -f /etc/netwall.conf ]; then
		cat /etc/netwall.conf > /tmp/netwall-rules
	elif [ -f /root/netwall-rules ]; then
		cat /root/netwall-rules > /tmp/netwall-rules
	else
		rm -f /tmp/netwall-rules
	fi

	cat /tmp/netwall-rules.tmp >> /tmp/netwall-rules
	rm -f /tmp/netwall-rules.tmp
else
	[ "$1" = "-6" ] && shift
fi

if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
	# iptables rules for OpenVPN client
	if [ -f /var/run/openvpn-client.pid ]; then
		iptables -I INPUT -i tun21 -j ACCEPT
		iptables -I OUTPUT -j ACCEPT
		iptables -I FORWARD -i tun21 -j ACCEPT
		iptables -I FORWARD -i br0 -o tun21 -j ACCEPT
		iptables -I FORWARD -i tun21 -o br0 -j ACCEPT
		iptables -t nat -A POSTROUTING -o tun21 -j MASQUERADE
	fi

	# Check if wg0 interface exists (WireGuard client), appply rules if yes
	ifconfig | grep -q wg0
	if [ $? -eq 0 ]; then
		iptables -I INPUT -i wg0 -j ACCEPT
		iptables -I OUTPUT -j ACCEPT
		iptables -I FORWARD -i wg0 -j ACCEPT
		iptables -I FORWARD -i br0 -o wg0 -j ACCEPT
		iptables -I FORWARD -i wg0 -o br0 -j ACCEPT
		iptables -t mangle -I FORWARD -o wg0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		iptables -t mangle -I FORWARD -i wg0 -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
		iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
	fi

	# Run own script with own iptables rules providing backward compatibility
	if [ -x /opt/scripts/firewall-start.sh ]; then
		/opt/scripts/firewall-start.sh
	elif [ -x /root/firewall-start.sh ]; then
		/root/firewall-start.sh
	fi
fi
