#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_THERMAL)		+= thermal_sys.o
obj-$(CONFIG_THERMAL_TSENS8960) += msm8960_tsens.o
obj-$(CONFIG_THERMAL_MONITOR)	+= msm_thermal.o
obj-$(CONFIG_SPEAR_THERMAL)		+= spear_thermal.o
