// JavaScript Document
//mulPPPoE 2
pppoe1="PPPoE セッション 1"
mul_session1="セッション 1"
mul_session2="セッション 2"
policy_setting="Trigger"
pppoe2_type="PPPoE Session 2 Type"
mulpppoe_setting_jp="ポリシー構成"
mulpppoe_MTU_Size="MTU サイズ (バイト)"
flet_square_pppoe_session="その他のPPPoE セッション/ NTT サービス情報サイト（旧フレッツ・スクウェア）"
pppoe2_enable="有効"
block_ser_port_range="ポート範囲"
info_mark_mulpppoe2="フレッツ・スクウェア/その他"
pppoe2_session_policy="PPPoE セッション 2 ポリシー"
block_ser_setup_ip_jp="IPアドレス"
invalid_ip="無効なIPアドレスです。 もう一度入力してください。\n"
//
basic_int_connection_mode="接続モード"
basic_mode_dial="要求に応じダイヤル"
basic_mode_always="常時接続"
basic_mode_manual="手動接続"


login_name_null="ログイン名は空欄にできません!"

device_title="NETGEAR ルータ"

table_bolder="<table border=1 cellpadding=2 cellspacing=0 width=100%>"
table_bolder0="<TABLE cellspacing=5 cellPadding=0 width=100% border=0>"
table_bg="<table width=600 border=2 cellpadding=2 cellspacing=0 bordercolor=#FFFFFF bgcolor=#E6E6E6>"
table_wel="<table border=0 cellpadding=10 cellspacing=10 width=720>"
table_100="<table width=100% height=100%>"
table_50="<table width=100% height=50%>"
bluebar="<TR><td colspan=2><img src=/liteblue.gif width=100% height=12></td></TR>"
hd_center="<td nowrap align=center>"
hd2="<td nowrap colspan=2>"
hdr4_center="<td nowrap align=center rowspan=4>"
hd="<td nowrap>"
hd_r="<td nowrap align=right>"
hd_top="<td valign=top height=300pt>"
hd2_center="<td nowrap colspan=2 align=center>"
hd3_center="<TD align=center colSpan=3 nowrap>"
hd_right="<td nowrap align=right>"
hd2_right="<td nowrap colspan=2 align=right>"
hd_35="<td width=35 align=center valign=middle>"
hd_550="<td width=550 valign=middle class=InductiveOptions>"
spacebar="<img src=/spacer.gif width=20 height=12 border=0>"
hp="<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>"
menu_str="<TD vAlign=top><IMG height=7  src=/rbullet.gif width=7 align=top vspace=6></TD>"
pro100="<br><table width=90\% border=0 cellpadding=0 cellspacing=0><tr bgcolor=#dddddd><td width=100\% bgcolor=#0099cc align=right>100\%</td><td width=0 class=tableRowb></td></tr></table>"
pro1="<br><table width=90% border=0 cellpadding=0 cellspacing=0><tr bgcolor=#dddddd><td width="
pro2="\% bgcolor=#0099cc align=right><font color=#ff0000>"
pro3="%</font></td><td width="
pro4="\%></td></tr></table>"
ba="</b></a>"

yes_mark=" はい"
no_mark=" いいえ"
apply_mark="適用"
cancel_mark="キャンセル"
refresh_mark="更新"
add_mark="追加"
edit_mark="編集"
delete_mark="削除"
test_mark="テスト"

/* pppoe */
basic_top_info="お使いのインターネット接続はログインを必要としていますか?"
basic_intserv_provider="インターネットサービスプロバイダ"
basic_intserv_pppoe="PPPoE"
basic_intserv_pptp="PPTP"
basic_intserv_bpa="Telstra Bigpond"
basic_intserv_mulpppoe="マルチ PPPoE"
basic_pppoe_login="ログイン"
basic_pppoe_passwd="パスワード"
basic_pppoe_serv_name="サービス名 (必要時のみ)"
basic_pppoe_idle="アイドルタイムアウト  (分)"
basic_int_intip="インターネット IP アドレス"
lan_mark_ip="IP アドレス"
basic_int_dns="ドメインネームサーバー (DNS) アドレス"
basic_int_autodns="プロバイダーから自動取得"
basic_int_these="DNS サーバーを指定（固定）"
basic_int_primary_dns="プライマリDNS"
basic_int_second_dns="セカンダリDNS"
basic_int_autoip="プロバイダーから自動取得"
basic_int_static_ip="IP アドレスを指定（固定）"

/* mulpppoe */
pppoe2_policy_setting="PPPoE セッション 2 ポリシー設定"
pppoe2="PPPoE セッション 2"
pppoe2_disable="無効"
pppoe2_west="NTT 西日本"
pppoe2_east="NTT 東日本"
pppoe2_other="その他"
mulpppoe_setting="ポリシー構成"
pppoe2_session_type="セッションタイプ"
pppoe2_domain_name="ドメイン名"
pppoe2_ip_address="IP アドレス"
pppoe2_port="ポート"
pppoe2_protocol="プロトコル"
pppoe2_ip_protocol="IP Address and Protocol"
pppoe2_port_protocol="Ports and Protocols"

internet_head="基本設定"
block_ser_setup_pro="プロトコル"
block_ser_setup_tcp="TCP"
block_ser_setup_udp="UDP"
block_ser_setup_tcp_udp="TCP/UDP"
block_ser_start_port="開始ポート"
block_ser_end_port="終了ポート"
block_ser_setup_filter="サービスをブロックするコンピューター"
block_ser_setup_thisip="この IP アドレスのみ:"
block_ser_setup_iprang="このIPアドレスのみ:"
block_ser_setup_to="から"
block_ser_setup_allip="すべてのIPアドレス"


