#!/bin/sh

config=/bin/config
upnp_enable=$($config get upnp_enable)

MINIUPNPD_CONF=/tmp/etc/miniupnpd.conf

print_upnp_conf() {
cat <<EOF
ext_ifname=$1
listening_ip=$2
port=5555
bitrate_up=1000000
bitrate_down=1000000
notify_interval=$3
time_to_live=$4
friendly_name=$5
listening_net=$6
allow 1024-65535 192.168.0.0/24 1024-65535
allow 1024-65535 192.168.1.0/24 1024-65535
allow 0-65535 0.0.0.0/0 0-65535
appsystem_location=http://updates1.netgear.com/$7/ww/$7.ddf
appsystem_os=$8
appsystem_product=${9}
non_igd=${10:-0}
EOF
}

upnp_start() {
	local proto=$($config get wan_proto)
	local appsystem_os_version="$(cat /proc/version |awk -F ' ' '{print $3}' |awk -F '.' '{print $1"."$2}')"
	local product_name=`cat /module_name |tr '[A-Z]' '[a-z]'`
	local appsystem_product=`echo $product_name |sed 's/v/\//'`

	if [ "$proto" = "pppoe" -o "$proto" = "pptp" -o "$proto" = "mulpppoe1" ]; then
		wan_ifname="ppp0"
	else
		wan_ifname=$($config get wan_ifname)
	fi

	local name=$($config get netbiosname)
	if [ "x$name" = "x" ]; then
		name=$($config get Device_name)
		[ "x$name" = "x" ] && [ -e /hardware_version ] && name="$(cat /hardware_version)"
	fi
	name="$name (Gateway)"

	local opmode=$($config get i_opmode)
	local non_igd=0
	if [ "$opmode" = "apmode" -o "$opmode" = "brmode" ] || \
		[ "$opmode" = "normal" -a "$upnp_enable" != "1" ]; then
		non_igd=1
	fi

	local listenip=$(ip addr show dev $($config get lan_ifname) |sed -n 's#.*inet \([0-9.]*\)/.*#\1#p')

	[ -f $MINIUPNPD_CONF ] && rm -f $MINIUPNPD_CONF
	[ ! -d /tmp/etc ] && mkdir /tmp/etc
	print_upnp_conf "$wan_ifname" "$listenip" "$($config get upnp_AdverTime)" "$($config get upnp_TimeToLive)" "$name" "$($config get lan_netmask)" "$product_name" "Linux/$appsystem_os_version" "$appsystem_product" "$non_igd" > $MINIUPNPD_CONF

	# wait a moment ...
	sleep 2

	if [ ! -f /sbin/kwilt ] && [ "$upnp_enable" = "0" ]; then
		echo "There is no kwilt and upnp is disabled, so do not start miniupnpd." > /dev/console
	else
		/usr/sbin/miniupnpd &
	fi

	if [ "$upnp_enable" = "0" ]; then
		sleep 2
		killall miniupnpd
	fi
}

case "$1" in
	stop)
		[ "$upnp_enable" = "1" ] && cp /tmp/upnp_pmlist /tmp/upnp_pmlist.bak 2>/dev/null
		killall miniupnpd
	;;
	start)
		[ "$upnp_enable" = "1" ] && cp /tmp/upnp_pmlist /tmp/upnp_pmlist.bak 2>/dev/null
		killall miniupnpd
		upnp_start
	;;
	restart)
		# To fix bug 22659, do nothing for "cmdupnp restart" command if /tmp/upnpIgnoreRestart exits
		[ -f /tmp/upnpIgnoreRestart ] && exit
		[ "$upnp_enable" = "1" ] && cp /tmp/upnp_pmlist /tmp/upnp_pmlist.bak 2>/dev/null
		killall miniupnpd
		upnp_start
	;;
esac
