#!/bin/sh

CONFIG=/bin/config

SMB_CONF_DIR=/tmp/config
SMB_PASSWD_DIR=/etc/samba/smbpasswd

# Unset
rm -f $SMB_CONF_DIR/passwd+
rm -f $SMB_CONF_DIR/gshadow
rm -f $SMB_CONF_DIR/shadow

# User setting
echo "root:!:0:0:root:/root:/bin/ash"			> $SMB_CONF_DIR/passwd
echo "guest:*:65534:65534:guest:/tmp/ftpadmin:/bin/ash"	>>$SMB_CONF_DIR/passwd
echo "nobody:*:65534:65534:nobody:/var:/bin/false" 	>>$SMB_CONF_DIR/passwd
echo "daemon:*:65534:65534:daemon:/var:/bin/false"	>>$SMB_CONF_DIR/passwd

echo "guest::10957:0:99999:7:::"                        >> $SMB_CONF_DIR/shadow

HTTP_PASSWD=$($CONFIG get http_passwd)

(sleep 1; echo "$HTTP_PASSWD"; sleep 1; echo "$HTTP_PASSWD") | /bin/adduser -G admin admin -H -h /tmp/ftpadmin -s /bin/ash
sed -i "s#$(/bin/cat /tmp/config/shadow | grep admin | cut -d ":" -f2)#$($CONFIG get dhx2_passwd)#g" /tmp/config/shadow

# Clear smbpasswd file
echo -n ""	> $SMB_PASSWD_DIR

# Create smbpasswd for root/admin/guest users
(echo ""; echo "") | smbpasswd -a root -s
sed -i "s/\:$(/bin/cat /etc/samba/smbpasswd | grep root | cut -d ":" -f4)\:\[/\:$($CONFIG get samba_passwd)\:\[/g" /etc/samba/smbpasswd
(echo ""; echo "") | smbpasswd -a admin -s
sed -i "s/\:$(/bin/cat /etc/samba/smbpasswd | grep admin | cut -d ":" -f4)\:\[/\:$($CONFIG get samba_passwd)\:\[/g" /etc/samba/smbpasswd
(echo ""; echo "") | smbpasswd -a guest -s

# RedyCLOUD
READYCLOUD_ENABLE=`$CONFIG get readycloud_enable`
if [ "$READYCLOUD_ENABLE" = "1" ]; then
i=0
id=500
while [ $i -le 9 ]; do
	READYCLOUD_USER="`$CONFIG get readycloud_user$i`"
	if [ "x$READYCLOUD_USER" != "x" ]; then
		USERNAME=`echo $READYCLOUD_USER | awk '{print $1}'`
		USERPASSWD=`echo $READYCLOUD_USER | awk '{print $3}'`
		echo "$USERNAME:x:$id:" >> $SMB_CONF_DIR/group
		(sleep 1; echo "$USERPASSWD"; sleep 1; echo "$USERPASSWD")| /bin/adduser -G $USERNAME $USERNAME -H -h /tmp/ftpadmin -s /bin/ash
		(echo "$USERPASSWD"; echo "$USERPASSWD") | smbpasswd -a $USERNAME
	else
		break;
	fi
	let i=$i+1
	let id=$id+1
done
fi
