#! /bin/sh

while [ 1 ]; do
	#1. check the time machine is running or not by the daemon pid
	flag=0
	if [ -f /tmp/pid_time_machine ]; then
		pid_time_machine=$(cat /tmp/pid_time_machine)
		flag=$(ps | grep admin | grep $pid_time_machine | wc -l)
	fi
	if [ $flag -eq 1 ]; then
		echo "Time Machine is running ... " > /dev/console
	else
		wol_pid=$(pidof send_wol)
		if [ "x$wol_pid" != "x" ]; then
			echo "Time Machine is stopped, we'll stop the daemon of send_wol!" > /dev/console
			kill -9 $wol_pid
		fi
	fi

	# 2.check the time machine is running or not by the afpd counts
	#afpd_num=$(ps | grep "afpd" | grep "admin" | wc -l)
	#wol_pid=$(pidof send_wol)
	#if [ $afpd_num -ge 2 ]; then
	#	echo "Time Machine is running ... " > /dev/console
		#if [ "x$wol_pid" = "x" ]; then
		#	/usr/sbin/send_wol 300 &
		#fi
	#else
	#	if [ "x$wol_pid" != "x" ]; then
	#		kill -9 $wol_pid
	#	fi
	#fi
	sleep 60
done
