#!/bin/sh /etc/rc.common

START=98
STOP=22

DROPBEAR="/usr/bin/dropbear"
PORT=22
PIDFILE="/var/run/dropbear.pid"

start() {
	# Start SSH server
	$DROPBEAR -p $PORT -a -s -P $PIDFILE
}

stop() {
	# Stop SSH server
	kill `cat $PIDFILE`
}
