#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=61

BIN=avahi-daemon
DEFAULT=/etc/default/$BIN
OPTIONS="-D"
RUN_D=/var/run/$BIN

start() {
	[ -f $DEFAULT ] && . $DEFAULT
	mkdir -p $RUN_D
	if [ ! -d /tmp/avahi/services ]; then
		mkdir -p /tmp/avahi/services
	fi
	for i in /usr/config/avahi/services/*; do
		if [ ! "`basename $i`" = "adisk.service" ]; then
			cp -f $i /etc/avahi/services
		fi
	done
	$BIN $OPTIONS  &
}

stop() {
  $BIN -k
}

reload() {
  $BIN -r
}

