#!/bin/sh

count=0
while [ 1 ]; do
    count=$((count + 1))
    if [ "x$count" = "x6" ]
    then
        count=0
        /usr/sbin/updateservice -imesBCbco 2>/dev/null
    fi
    /usr/sbin/deal-mdns-result 2>/dev/null
    sleep 8
done

