#!/bin/sh

#enable debug or not
comment=#

#[ ! -f /tmp/mywifiext.service ] && $(cp /etc/avahi/services/mywifiext.service /tmp/mywifiext.service)

updateNodeValue(){
    eval "sed -i '$1s/<txt-record>.*<\/txt-record>/<txt-record>$2=$OPTARG<\/txt-record>/' /etc/avahi/mywifiext.service"
}

format_ip(){
    ipd1=$(echo $1 | cut -d . -f 1 | awk '{printf("%02X", $0)}')
    ipd2=$(echo $1 | cut -d . -f 2 | awk '{printf("%02X", $0)}')
    ipd3=$(echo $1 | cut -d . -f 3 | awk '{printf("%02X", $0)}')
    ipd4=$(echo $1 | cut -d . -f 4 | awk '{printf("%02X", $0)}')
    echo "$ipd1$ipd2$ipd3$ipd4"
}


format(){
    ip=$(sed -n '8s/<txt-record>ip=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service)
    ip=$(format_ip $ip)
    len=20
    ver=$(sed -n '9s/<txt-record>ver=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
    mac=$(sed -n '10s/<txt-record>mac=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | sed 's/://g')
#    name=$(sed -n '11s/<txt-record>name=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service)
#    extvie=$(sed -n '12s/<txt-record>extvie=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | sed 's/ //g')
#    [ "$extvie" = "" ] && extvie=0000000000000000
#    mdns_joined=$(sed -n '13s/<txt-record>mdns_joined=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
    extvie=$(sed -n '11s/<txt-record>extvie=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | sed 's/ //g')
    [ "$extvie" = "" ] && extvie=0000000000000000
    mdns_joined=$(sed -n '12s/<txt-record>mdns_joined=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
#    mac_5g1=$(sed -n '14s/<txt-record>5G1_bssid=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | sed -e 's/://g' -e 's/ //g')
#    [ "$mac_5g1" = "Not-Associated" ] && mac_5g1=000000000000
#    chan_5g1=$(sed -n '15s/<txt-record>5G1_channel=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
#    mac_5g2=$(sed -n '16s/<txt-record>5G2_bssid=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | sed -e 's/://g' -e 's/ //g')
#    [ "$mac_5g2" = "Not-Associated" ] && mac_5g2=000000000000
#    chan_5g2=$(sed -n '17s/<txt-record>5G2_channel=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
#    mac_2g=$(sed -n '18s/<txt-record>2G_bssid=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service| sed -e 's/://g' -e 's/ //g')
#    [ "$mac_2g" = "Not-Associated" ] && mac_2g=000000000000
#    chan_2g=$(sed -n '19s/<txt-record>2G_channel=\(.*\)<\/txt-record>/\1/p' /etc/avahi/mywifiext.service | awk '{printf("%02X", $0)}')
#    data=$(echo "$ver $len $mac $extvie $mdns_joined $ip $mac_2g $chan_2g $mac_5g1 $chan_5g1 $mac_5g2 $chan_5g2 $name" | sed 's/ //g')
    data=$(echo "$ver $len $mac $extvie $mdns_joined $ip R7800" | sed 's/ //g')
    eval "sed -i '7s/<txt-record>.*<\/txt-record>/<txt-record>$data<\/txt-record>/' /etc/avahi/services/mywifiext.service"
}

usage(){
    echo -e "\
Usage:\n\
    -i update host ip\n\
    -m update host mac\n\
    -e update host extvie\n\
    -s update host mdns_joined\n\
    -b update host 5g1_bssid and 5g2_bssid\n\
    -c update host 5g1_channel and 5g2_channel\n\
    -B update host 2g_bssid\n\
    -C update host 2g_channel\n\
    -o optput txt record with mywifiext.service\n\
    -h dump help\n "
}

while getopts :imesbcBCo arg
do
    case $arg in
        i)
            tmp=$(ifconfig br0 | grep "inet addr" | awk '{print $2}')
            OPTARG=${tmp#*:}
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 8 ip
            ;;
        m)
            OPTARG=$(ifconfig br0 | grep HWaddr | awk '{print $5}')
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 10 mac
            ;;
        e)
            OPTARG=$(wlanconfig ath1 vendorie list | grep -A 1 "00146c" | sed 's/ //g' | awk -F: 'NR==2{print $2}')
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 11 extvie
            ;;
        s)
            OPTARG=1
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 12 mdns_joined
            ;;
        b)
            OPTARG=$(iwconfig ath0 | grep Point | awk '{print $6}')
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 13 5G1_bssid
            ;;
        c)
            tmp=$(iwlist ath0 channel | grep Current | awk '{print $5}')
            OPTARG=$(echo ${tmp%)})
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 14 5G1_channel
            ;;
        B)
            OPTARG=$(iwconfig ath1 | grep Point | awk '{print $6}')
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 15 2G_bssid
            ;;
        C)
            tmp=$(iwlist ath1 channel | grep Current | awk '{print $5}')
            OPTARG=$(echo ${tmp%)})
            eval "$comment echo \"$OPTARG\""
            update=1
            updateNodeValue 16 2G_channel
            ;;
        o)
            eval "$comment echo \"$OPTARG\""
            output=1
            ;;
        h)
            usage
            ;;
        :)
            echo "option -$OPTARG miss argument "
            exit 1
            ;;
        ?)
            echo "invalid option"
            usage
            exit 0
            ;;
    esac
done

if [ "$update" = "1" ]; then
    #cp /tmp/mywifiext.service /etc/avahi/services/mywifiext.service
    format
    killall -SIGHUP avahi-daemon
    sleep 2
fi

if [ "$output" = "1" ]; then
    querier && sleep 2
    killall -SIGUSR1 avahi-daemon && sleep 3
    cat /tmp/mdns_record_tmp | sort -u | grep mywifiext > /tmp/mdns_record_format
    /usr/sbin/format_record
fi

exit 0
