# MSM CPU/CODEC DAI Support


# MSM Platform Support
obj-$(CONFIG_SND_MSM_SOC) += snd-soc-msm.o

obj-$(CONFIG_SND_MSM7KV2_SOC) += snd-soc-msmv2.o

# MSM Machine Support
obj-$(CONFIG_SND_MSM_SOC_MSM7K) += snd-soc-msm7k.o

obj-$(CONFIG_SND_MSM_SOC_MSM7KV2) += snd-soc-msm7kv2.o

# 8660 ALSA Support




#MVS Support


# 8660 ALSA Support
obj-$(CONFIG_SND_SOC_MSM8660_LPAIF) += snd-soc-lpass.o


#8660 VOIP Driver Support



# for MSM 8960 sound card driver

obj-$(CONFIG_SND_SOC_QDSP6) += snd-soc-qdsp6.o


# Generic MSM drivers
obj-$(CONFIG_SND_SOC_MSM_HOSTLESS_PCM) += snd-soc-hostless-pcm.o

obj-$(CONFIG_SND_SOC_MSM8660_APQ) += snd-soc-msm8660-apq.o

# for MDM 9615 sound card driver

# for MSM 8974 sound card driver
obj-$(CONFIG_SND_SOC_MSM_QDSP6V2_INTF) += qdsp6v2/

obj-$(CONFIG_SND_SOC_QDSP6V2) += snd-soc-qdsp6v2.o

