#------------------------------------------------------------------------------
# Copyright (c) 2013 Qualcomm Atheros, Inc.
# All Rights Reserved.
# Qualcomm Atheros Confidential and Proprietary.
#------------------------------------------------------------------------------

!INCLUDE $(_MAKEENVROOT)\makefile.def



