#IPQ LPASS SND CARD

snd-soc-ipq806x-objs := ipq806x.o
snd-soc-ipq806x-clk-objs := ipq-lpass-clk.o
snd-soc-ipq-pcm-raw-objs := ipq-pcm-raw.o ipq-pcm-raw-lb-test.o
snd-soc-ipq-pcm-mi2s-objs := ipq-pcm-mi2s.o
snd-soc-ipq-pcm-spdif-objs := ipq-pcm-spdif.o
snd-soc-ipq-pcm-voip-objs := ipq-pcm-voip.o
snd-soc-ipq-spdif-objs := ipq-spdif.o
snd-soc-ipq-lpass-codec-objs := ipq-lpass-codec.o
snd-soc-ipq-lpass-codec-objs += ipq-mi2s-codec.o ipq-spdif-codec.o
snd-soc-ipq-lpass-codec-objs += ipq-pcm-codec.o
snd-soc-ipq-cpu-dai-objs := ipq-cpu-dai.o
snd-soc-ipq-dmlite-objs := ipq-dmlite.o
snd-soc-ipq-lpaif-objs := ipq-lpaif.o

obj-$(CONFIG_SND_IPQ_SOC_IPQ806X) += snd-soc-ipq806x.o
obj-$(CONFIG_SND_IPQ_SOC_CLK) += snd-soc-ipq806x-clk.o
obj-$(CONFIG_SND_IPQ_SOC_PCM_RAW) += snd-soc-ipq-pcm-raw.o
obj-$(CONFIG_SND_IPQ_SOC_PCM_I2S) += snd-soc-ipq-pcm-mi2s.o
obj-$(CONFIG_SND_IPQ_SOC_PCM_SPDIF) += snd-soc-ipq-pcm-spdif.o
obj-$(CONFIG_SND_IPQ_SOC_PCM_VOIP) += snd-soc-ipq-pcm-voip.o
obj-$(CONFIG_SND_IPQ_SOC_SPDIF) += snd-soc-ipq-spdif.o
obj-$(CONFIG_SND_IPQ_SOC_LPASS_CODEC) += snd-soc-ipq-lpass-codec.o
obj-$(CONFIG_SND_IPQ_SOC_CPU_DAI) += snd-soc-ipq-cpu-dai.o
obj-$(CONFIG_SND_IPQ_SOC_DMLITE) += snd-soc-ipq-dmlite.o
obj-$(CONFIG_SND_IPQ_SOC_LPAIF) += snd-soc-ipq-lpaif.o
