#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=50

CRONTABS=/tmp/etc/crontabs
CRON_SPOOL=/var/spool/cron
CRON_ROOT_FILE=${CRONTABS}/root

start () {

	mkdir -p $CRON_SPOOL
	[ -d $CRONTABS ] && rm -fr $CRONTABS
	mkdir -p $CRONTABS
	[ -L ${CRON_SPOOL}/crontabs ] || ln -s $CRONTABS ${CRON_SPOOL}/crontabs

	# Generate `Block Sites` && `Block Services` && `E-mail Notification`
	# for scheduling.
	# This `firewall_function.sh` script will call `/sbin/cmdsched`, then
	# re-start firewall setting.
	/www/cgi-bin/firewall_function.sh blk_sched restart

	# Start NTP when `time_zone` is reset.

	crond -c $CRONTABS -T "$($CONFIG get time_zone)"
}

stop() {
	killall -9 crond
}

restart() {
	stop
	start
}
